services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graph-db
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/venev  # password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/import

    restart: always